export const Actions = {
  ADD_USER: 'ADD_USER',
  SET_USER: 'SET_USER',
  SET_ACTIVE_RESOURCE: 'SET_ACTIVE_RESOURCE',
  ADD_ORGANIZATION: 'ADD_ORGANIZATION',
  ADD_PROJECT: 'ADD_PROJECT',
  ADD_TASK: 'ADD_TASK'
};
