name: Run tests
on: [push]
env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_URL: ${{ secrets.BASE_URL }}
  GRAPHQL_TOKEN_GITHUB: ${{ secrets.GRAPHQL_TOKEN_GITHUB }}
  GRAPHQL_URL_GITHUB: ${{ secrets.GRAPHQL_URL_GITHUB }}
jobs:
  build-frontend-run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1]
    steps:
      - name: Setup FE ENV Variables
        run: |
          echo "BASE_URL=${BASE_URL}" >> .env
          echo "GRAPHQL_TOKEN_GITHUB=${GRAPHQL_TOKEN_GITHUB}" >> .env
          echo "GRAPHQL_URL_GITHUB=${GRAPHQL_URL_GITHUB}" >> .env
      - name: Checkout frontend
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build frontend
        run: npm run build

      - name: Run local tests
        run: npm run test

      - name: Checkout Cypress repo
        uses: actions/checkout@v4
        with:
          repository: danfyfe/dans-coconuts-cypress
          path: ./cypress-tests

      - name: Upload Cypress Config
        uses: actions/upload-artifact@v4
        with:
          name: cypress-config
          path: ./cypress-tests/cypress.config.ts

      - name: Download Cypress Config
        uses: actions/download-artifact@v4
        with:
          name: cypress-config
          path: ./

      - name: Install Cypress decpendencies
        run: npm install
        working-directory: ./cypress-tests

      # this step will not complete itself, so a timout is needed
      # it will start the app, then wait, moving on as if it was canceled
      - name: Start frontend
        run: npm start
        timeout-minutes: 1
        continue-on-error: true
        working-directory: ./

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: "http://localhost:3001"
          record: true
          working-directory: ./cypress-tests
