name: Run tests
on: [push]
jobs:
  build-frontend-run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1]
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build frontend
        run: npm run build

      - name: Run local tests
        run: npm run test

      - name: Checkout Cypress repo
        uses: actions/checkout@v4
        with:
          repository: danfyfe/dans-coconuts-cypress
          path: ./cypress-tests

      - name: Upload Cypress Config
        uses: actions/upload-artifact@v4
        with:
          name: cypress-config
          path: ./cypress-tests/cypress.config.ts

      - name: Download Cypress Config
        uses: actions/download-artifact@v4
        with:
          name: cypress-config
          path: ./

      - name: Install Cypress decpendencies
        run: npm install
        working-directory: ./cypress-tests

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          working-directory: ./cypress-tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # cypress-run:
  #   runs-on: ubuntu-latest
  #   # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
  #   # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
  #   # Also see warning here https://github.com/cypress-io/github-action#parallel
  #   strategy:
  #     fail-fast: false # https://github.com/cypress-io/github-action/issues/48
  #     matrix:
  #       containers: [1, 2] # Uses 2 parallel instances
  #   steps:
  #     - name: Checkout e2e tests
  #       uses: actions/checkout@v4
  #       with:
  #         repository: danfyfe/danscoconuts-cypress
  #         path: ./e2e-tests
  # - name: Cypress run
  #   # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
  #   uses: cypress-io/github-action@v6
  #   with:
  #     browser: chrome
  #     wait-on: "http://localhost:3000" # Waits for above
  #     # Records to Cypress Cloud
  #     # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
  #     record: true
  #     parallel: true # Runs test in parallel using settings above
  #   env:
  #     # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
  #     # in GitHub repo → Settings → Secrets → Actions
  #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #     # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
